config/routes.rb
Rails.application.routes.draw do

   # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get '/tasks', to: 'tasks#index', as: :tasks

  # Route to create a new task
  get '/tasks/new', to: 'tasks#new', as: :new_task

  # Route to view a single task
  get '/tasks/:id', to: 'tasks#show', as: :task

  # Route to create a new task
  post '/tasks', to: 'tasks#create'

  # Route to edit a task
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  # Route to update a task
  patch '/tasks/:id', to: 'tasks#update'

  # Route to delete a task
  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  # Strong parameters for task
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>New Task</h1>

<%= form_with(model: @task) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details, class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="actions">
    <%= form.submit 'Update task', class:"btn btn-primary" %>
    <%# <%= link_to 'submit', create_task_path%>
  </div>
<% end %>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks</h1>
  <ul>
   <% @tasks.each do |task| %>
    <li><% if task.completed %>
      <i class="fa-regular fa-square-check"></i>
    <% else %>
        <i class="fa-regular fa-square"></i>
    <% end %>
    <%= link_to task.title, task_path(task.id) %> - <%= link_to task_path(task.id), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Delete #{task.title}?" }, class: 'delete-task' do %>
    <i class="fa-solid fa-trash-can"></i>
    <% end %></li>
      <%= link_to 'New task', new_task_path%>
   <% end %>
  </ul>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with(model: @task) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details, class:"form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Task', class:"btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><strong>Details:</strong> <%= @task.details %></p>
<p><strong>Status:</strong> <%= @task.completed ? 'Completed' : 'Not Completed' %></p>
<%= link_to 'Update task', edit_task_path, class:"btn"%>
<%= link_to 'Back', tasks_path %>

app/views/tasks/tasks.html.erb
<div class="container">
  <h1>My tasks</h1>
</div>